FROM openjdk:21
VOLUME /tmp
ARG JAR_FILE
ARG TRIBES_DB_URL
ARG TRIBES_DB_USR
ARG TRIBES_DB_PWD
ARG TRIBES_WEB_PORT
ARG DB_REBUILD
ARG TRIBES_JWT_SECRET
ARG TRIBES_TOKEN_SECRET

ENV TRIBES_DB_URL $TRIBES_DB_URL
ENV TRIBES_DB_USR $MYSQL_USR
ENV TRIBES_DB_PWD $MYSQL_PASSWORD
ENV TRIBES_WEB_PORT $TRIBES_WEB_PORT
ENV DB_REBUILD $DB_REBUILD
ENV TRIBES_JWT_SECRET $TRIBES_JWT_SECRET
ENV TRIBES_TOKEN_SECRET $TRIBES_TOKEN_SECRET

RUN echo $JAR_FILE
RUN mkdir -p /gda/tribes
COPY $JAR_FILE "./TribesVibinAndTribinOtocyon"
ENTRYPOINT ["java", "-jar", "./TribesVibinAndTribinOtocyon"]
