version: "3.7"
services:
  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    healthcheck:
      test: echo '\q' | mysql --user=root --password=password || exit 1
      interval: 5s
      timeout: 30s
      retries: 60
      start_period: 10s

  noty:
    image: schimiuss/tribes:latest
    ports:
      - "8088:80"
    environment:
      TRIBES_DB_URL: $TRIBES_DB_URL
      TRIBES_DB_USR: $MYSQL_USER
      TRIBES_DB_PWD: $MYSQL_PASSWORD
      DB_REBUILD: update
      TRIBES_JWT_SECRET: $TRIBES_JWT_SECRET
      TRIBES_TOKEN_SECRET: $TRIBES_TOKEN_SECRET
      TRIBES_WEB_PORT: $TRIBES_WEB_PORT
    depends_on:
      mysql-server:
        condition: service_healthy
    links: 
      - mysql-server
